name: Android CI

on:
  push:
    branches: [ android-port ]
  pull_request:
    branches: [ android-port ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: cd to android
      run: cd android
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: srb2
        path: android/app/build/outputs/apk/gameFull/
